/**
	@file BinaryXmlDef.h
	@brief evtx 바이너리 XML에서 사용하는 상수값들
*/

#ifndef _BINARY_XML_DEF_H_
#define _BINARY_XML_DEF_H_

#define BIN_XML_TOKEN_EOF						0x00
#define BIN_XML_TOKEN_OPEN_START_ELEMENT		0x01
#define BIN_XML_TOKEN_CLOSE_START_ELEMENT		0x02
#define BIN_XML_TOKEN_CLOSE_EMPTY_ELEMENT		0x03
#define BIN_XML_TOKEN_END_ELEMENT_TAG			0x04
#define BIN_XML_TOKEN_VALUE						0x05
#define BIN_XML_TOKEN_ATTRIBUTE					0x06
#define BIN_XML_TOKEN_CDATA_SECTION				0x07
#define BIN_XML_TOKEN_CHAR_REF					0x08
#define BIN_XML_TOKEN_ENTITY_REF				0x09
#define BIN_XML_TOKEN_PI_TARGET					0x0A
#define BIN_XML_TOKEN_PI_DATA					0x0B
#define BIN_XML_TOKEN_TEMPLATE_INSTANCE			0x0C
#define BIN_XML_TOKEN_NORMAL_SUBSTITUTE			0x0D
#define BIN_XML_TOKEN_OPTIONAL_SUBSTITUTE		0x0E
#define BIN_XML_TOKEN_FRAGMENT_HEADER			0x0F

#define GET_TOKEN(x) ((x) & 0x0F)
#define HAS_MORE_DATA(x) ((x) & 0x40)

#define BIN_XML_VALUE_NULL						0x00
#define BIN_XML_VALUE_STRING					0x01
#define BIN_XML_VALUE_ANSI_STRING				0x02
#define BIN_XML_VALUE_INT_8						0x03
#define BIN_XML_VALUE_UINT_8					0x04
#define BIN_XML_VALUE_INT_16					0x05
#define BIN_XML_VALUE_UINT_16					0x06
#define BIN_XML_VALUE_INT_32					0x07
#define BIN_XML_VALUE_UINT_32					0x08
#define BIN_XML_VALUE_INT_64					0x09
#define BIN_XML_VALUE_UINT_64					0x0A
#define BIN_XML_VALUE_REAL_32					0x0B
#define BIN_XML_VALUE_REAL_64					0x0C
#define BIN_XML_VALUE_BOOL						0x0D
#define BIN_XML_VALUE_BINARY					0x0E
#define BIN_XML_VALUE_GUID						0x0F
#define BIN_XML_VALUE_SIZE_T					0x10
#define BIN_XML_VALUE_FILE_TIME					0x11
#define BIN_XML_VALUE_SYS_TIME					0x12
#define BIN_XML_VALUE_SID						0x13
#define BIN_XML_VALUE_HEX_INT32					0x14
#define BIN_XML_VALUE_HEX_INT64					0x15
#define BIN_XML_VALUE_EVT_HANDLE				0x20
#define BIN_XML_VALUE_BIN_XML					0x21
#define BIN_XML_VALUE_EVT_XML					0x22

#define BIN_XML_VALUE_ARRAY_STRING				0x81
#define BIN_XML_VALUE_ARRAY_ANSI_STRING			0x82
#define BIN_XML_VALUE_ARRAY_INT_8				0x83
#define BIN_XML_VALUE_ARRAY_UINT_8				0x84
#define BIN_XML_VALUE_ARRAY_INT_16				0x85
#define BIN_XML_VALUE_ARRAY_UINT_16				0x86
#define BIN_XML_VALUE_ARRAY_INT_32				0x87
#define BIN_XML_VALUE_ARRAY_UINT_32				0x88
#define BIN_XML_VALUE_ARRAY_INT_64				0x89
#define BIN_XML_VALUE_ARRAY_UINT_64				0x8A
#define BIN_XML_VALUE_ARRAY_REAL_32				0x8B
#define BIN_XML_VALUE_ARRAY_REAL_64				0x8C
#define BIN_XML_VALUE_ARRAY_BOOL				0x8D
#define BIN_XML_VALUE_ARRAY_BINARY				0x8E
#define BIN_XML_VALUE_ARRAY_GUID				0x8F
#define BIN_XML_VALUE_ARRAY_SIZE_T				0x80
#define BIN_XML_VALUE_ARRAY_FILE_TIME			0x91
#define BIN_XML_VALUE_ARRAY_SYS_TIME			0x92
#define BIN_XML_VALUE_ARRAY_SID					0x93
#define BIN_XML_VALUE_ARRAY_HEX_INT32			0x94
#define BIN_XML_VALUE_ARRAY_HEX_INT64			0x95

#endif /* _BINARY_XML_DEF_H_ */